name: Publish Python Package to PyPI

# Trigger on version tags (v1.0.0, v1.0.1, etc.)
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    # Use trusted publishing (recommended by PyPI)
    environment: 
      name: pypi
      url: https://pypi.org/p/firehound-scanner
    permissions:
      id-token: write    # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write    # Required to create GitHub releases
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Extract version from tag
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Releasing version: $VERSION"
        
    - name: Update version in pyproject.toml
      run: |
        # Update version in pyproject.toml to match git tag
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        echo "Updated pyproject.toml version to: $VERSION"
        cat pyproject.toml | grep "^version"
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        python -m twine check dist/*
        
    - name: Publish package to PyPI using Trusted Publishing
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No token needed with trusted publishing!
        print-hash: true
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.VERSION }}
        body: |
          ## Changes in v${{ env.VERSION }}
          
          ### ✅ What's New
          - Add your release notes here
          - List key changes and improvements
          
          ### 📦 Installation
          ```bash
          pip install firehound-scanner==${{ env.VERSION }}
          # or
          pipx install firehound-scanner==${{ env.VERSION }}
          ```
          
          ### 🔗 Links
          - [PyPI Package](https://pypi.org/project/firehound-scanner/${{ env.VERSION }}/)
          - [Documentation](https://github.com/covertlabsaus/firehound/blob/main/README.md)
        draft: false
        prerelease: false
